# == In this configuration, you set up Alchemy's element layouts.
#
# For further information please see http://guides.alchemy-cms.com/stable/elements.html

- name: article
  hint: true
  unique: true
  contents:
  - name: headline
    type: EssenceText
    default: :article_headline
    hint: true
  - name: picture
    type: EssencePicture
    hint: true
  - name: text
    type: EssenceRichtext
    default: :article_text
    hint: true


- name: blog_title
  unique: true
  contents:
    - name: title
      type: EssenceText
      default: Blog
    - name: text
      type: EssenceText
      default: This is a blog template

- name: blog_post
  contents:
    - name: blog_post_title
      type: EssenceText
      default: Blog Post Title
      settings:
        linkable: true
    - name: blog_post_meta
      type: EssenceText
      default: "Made by GastroDev2020"
    - name: blog_post_intro_text
      type: EssenceRichtext
    - name: blog_post_image
      type: EssencePicture
    - name: blog_post_content
      type: EssenceRichtext



- name: categories_block
  contents:
    - name: categories_headline
      type: EssenceText
      default: Categories
      nestable_elements:
        - category

- name: category
  contents:
    - name: name
      type: EssenceText
      settings:
        linkable: true


- name: featured
  unique: true
  contents:
    - name: featured_headline
      type: EssenceText
      default: "Featured"
    - name: featured_text
      type: EssenceRichtext
    - name: featured_link
      type: EssenceText
      settings:
        linkable: true
